// Auth Type
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_START='USER_LOGIN_START'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'

export const KEEP_LOGIN='KEEP_LOGIN'

// Register Type
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_START='USER_REGISTER_START'
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED'

