// Login Type
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_START='USER_LOGIN_START'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'
export const KEEP_LOGIN='KEEP_LOGIN'

// Register Type
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_START='USER_REGISTER_START'
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED'

// Send Email Verification
export const SEND_EMAIL_SUCCESS='SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_START= 'SEND_EMAIL_START'

// Verified
export const VERIFY_START='VERIFY_START'
export const VERIFY_SUCCESS='VERIFY_SUCCESS'
export const VERIFY_FAILED='VERIFY_FAILED'

// Forgot password
export const SEND_EMAIL_PASSWORD_SUCCESS='SEND_EMAIL_PASSWORD_SUCCESS'
export const SEND_EMAIL_PASSWORD_START= 'SEND_EMAIL_PASSWORD_START'
export const SEND_EMAIL_PASSWORD_FAILED= 'SEND_EMAIL_PASSWORD_FAILED'

// Reset password
export const RESET_PASSWORD_SUCCESS='RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_START= 'RESET_PASSWORD_START'
export const RESET_PASSWORD_FAILED= 'RESET_PASSWORD_FAILED'

// Check if token exist
export const TOKEN_EXIST='TOKEN_EXIST'
export const TOKEN_NOT_EXIST='TOKEN_NOT_EXIST'

// Logout
export const USER_LOGOUT='USER_LOGOUT'